// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqOJSS-4ZE_keufHAiQJolE1dRleF2xFE',
    appId: '1:958809572043:web:6032fae2e72ec36b85114e',
    messagingSenderId: '958809572043',
    projectId: 'spazio-5544b',
    authDomain: 'spazio-5544b.firebaseapp.com',
    storageBucket: 'spazio-5544b.firebasestorage.app',
    measurementId: 'G-B13K1F0MND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6AfgEDz76Q0akEWm0VNyBOMm2Wt7iQL0',
    appId: '1:958809572043:android:2ae1246b2b966f9185114e',
    messagingSenderId: '958809572043',
    projectId: 'spazio-5544b',
    storageBucket: 'spazio-5544b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz7Bx4sCL6lQl0kGhRt5OvUBmbkRwEMrE',
    appId: '1:958809572043:ios:bd53d1e197f5389e85114e',
    messagingSenderId: '958809572043',
    projectId: 'spazio-5544b',
    storageBucket: 'spazio-5544b.firebasestorage.app',
    iosBundleId: 'com.example.eWize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz7Bx4sCL6lQl0kGhRt5OvUBmbkRwEMrE',
    appId: '1:958809572043:ios:bd53d1e197f5389e85114e',
    messagingSenderId: '958809572043',
    projectId: 'spazio-5544b',
    storageBucket: 'spazio-5544b.firebasestorage.app',
    iosBundleId: 'com.example.eWize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqOJSS-4ZE_keufHAiQJolE1dRleF2xFE',
    appId: '1:958809572043:web:c0465ee5bbe2c8bd85114e',
    messagingSenderId: '958809572043',
    projectId: 'spazio-5544b',
    authDomain: 'spazio-5544b.firebaseapp.com',
    storageBucket: 'spazio-5544b.firebasestorage.app',
    measurementId: 'G-1GD73JSTQ0',
  );
}
